language: node
sudo: required
language: node_js
node_js: 6

cache:
  directories:
  - node_modules

env:
  global:
  - BX_APP: bx-blue-green-test
  - BX_API: https://api.ng.bluemix.net
  - BX_ORGANIZATION: andres.villa
  - BX_SPACE: dev
  - secure: BuTCwhlxFCsXH0slmLiZcV04oUCfHlTc6hjHuEJsFpHdhgiV+0Bqbl7VcwbAQOUMEx7MSiOJVhYXf5FAjJKXvlnKrrJbMhfV3puvjghwlVpnv2tHXXpCkoIU4oPmigbYWPTWFl84HtSDqvLtYRtRn0ElnIt7iF1MVjFBw3v0sagZEePZ8yLIrP/Y7is5+I5dy+DO4TphbZR259Rif0rpvdsPZyLqWHeG6PR690rHZYxecRAfDJ+VCEFPfVhL3ghaUjtaK6oapz/3aK6u1xy8W0A7HZ9SuVIUvy1tKJAyX6Rpv00S2VNo4u3lcHDlYyVj/TEwVpxj+xTmgDMM4pjn2PuJWIBpQDSOO6BDYF+lprDPw8uaG4cyYHemc4hxoPoe9Tyg90UVwdteA1NydryIUFVVba1STdpbS2HG59CwMFQyxU0QeMH4VOPYSRIatz3dIhecktEz6OGNKXSCLaDEgr/H53AgaeaLRtWaqDrJ1HKTzeNLGF6xgj5bIBz57mMQws8jkgXGW6748Ujq7aTKcGyUPEKWWsN16tJlz7D1G+IVtyLc0fUGCMp96nw7mVNCE6N4AGGuPoOMiidpVkvd4DFx4kFhacNOW9zUpHw6bEiTIYJHV9u0OoU98OjADYUuQWusp9R5iJNUSeGPBVT57+fxAZmN6T+gAgaJSZZqZto=
before_deploy: npm install -g bx-blue-green
deploy:
  provider: script
  script:
  - bx-blue-green-travis
  on:
    branch: master
notifications:
  email: true
